spring:
  application:
    name: jhosep_evaluacionBack
  datasource:
    url: jdbc:postgresql://localhost:5432/evaluacion_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: jhosepEvaluacionSecretKeyForJWTTokenGenerationAndValidation2024SystemDevelopment
    expiration: 86400000